name: Elisp CI

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Enables manual triggering
  pull_request:

jobs:
  byte-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Emacs
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y emacs-nox
          emacs --version

      - name: Byte-compile
        shell: bash
        run: |
          set -euxo pipefail
          emacs -Q --batch -L . -f batch-byte-compile agentic.el
